"""added games played

Revision ID: 05a623421195
Revises: a79d2fcafca3
Create Date: 2025-02-18 22:50:11.630422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05a623421195'
down_revision: Union[str, None] = 'a79d2fcafca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'averageWPM',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('stats', 'highestWPM',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'highestWPM',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('stats', 'averageWPM',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
