"""added username foreign key

Revision ID: 1ba88800dc0b
Revises: a10e6847c8fb
Create Date: 2025-02-19 11:00:52.649769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ba88800dc0b'
down_revision: Union[str, None] = 'a10e6847c8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stats_ibfk_1', 'stats', type_='foreignkey')
    op.drop_column('stats', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True))
    op.create_foreign_key('stats_ibfk_1', 'stats', 'users', ['user_id'], ['uid'])
    # ### end Alembic commands ###
