"""got rid of hashed password, using firebase auth

Revision ID: 3e00cf7cd015
Revises: bf4ebfcec9f8
Create Date: 2025-02-16 14:35:24.183056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e00cf7cd015'
down_revision: Union[str, None] = 'bf4ebfcec9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stats', 'users', ['user_id'], ['uid'])
    op.add_column('users', sa.Column('uid', sa.String(length=255), nullable=False))
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'uid')
    op.drop_constraint(None, 'stats', type_='foreignkey')
    # ### end Alembic commands ###
