"""got rid of hashed password, using firebase auth

Revision ID: 51d5757674f9
Revises: a2da153c53e3
Create Date: 2025-02-16 14:54:39.636304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d5757674f9'
down_revision: Union[str, None] = 'a2da153c53e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
