"""got rid of hashed password, using firebase auth

Revision ID: 7a080ce8e936
Revises: 9c2c3e53c0e9
Create Date: 2025-02-16 14:30:59.241715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a080ce8e936'
down_revision: Union[str, None] = '9c2c3e53c0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'user_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(None, 'stats', 'users', ['user_id'], ['uid'])
    op.add_column('users', sa.Column('uid', sa.String(length=255), nullable=False))
    op.drop_index('ix_users_id', table_name='users')
    op.create_unique_constraint(None, 'users', ['uid'])
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'uid')
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.alter_column('stats', 'user_id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
