"""added username foreign key

Revision ID: a10e6847c8fb
Revises: 047b26f1bd1b
Create Date: 2025-02-19 10:57:31.710287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10e6847c8fb'
down_revision: Union[str, None] = '047b26f1bd1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('username', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'stats', 'users', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.drop_column('stats', 'username')
    # ### end Alembic commands ###
