"""moved games played to stats

Revision ID: a79d2fcafca3
Revises: 61962171a5b8
Create Date: 2025-02-17 10:18:58.950990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a79d2fcafca3'
down_revision: Union[str, None] = '61962171a5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('games_played', sa.Integer(), nullable=False))
    op.drop_column('users', 'games_played')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('games_played', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('stats', 'games_played')
    # ### end Alembic commands ###
