"""got rid of hashed password, using firebase auth

Revision ID: c70e993ae7ef
Revises: b15d43a61138
Create Date: 2025-02-16 14:18:15.039763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c70e993ae7ef'
down_revision: Union[str, None] = 'b15d43a61138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stats', 'users', ['user_id'], ['uid'])
    op.add_column('users', sa.Column('uid', sa.Integer(), nullable=False))
    op.drop_index('ix_users_id', table_name='users')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'uid')
    op.drop_constraint(None, 'stats', type_='foreignkey')
    # ### end Alembic commands ###
